### ISSUE TITLE
aws-node-rest-api-with-dynamodb - dynamodb isn't removed with `sls remove`

### ISSUE THREAD

**Issue by ozbillwang** [serverless/examples#198] opened 2017-09-23 23:13 UTC
i have successfully deploy `aws-node-rest-api-with-dynamodb-and-offline`, then I want to remove all sls resources 

    sls remove

My understanding is, all resources created before should be removed. But seems I need to remove dynamodb manually. 

Is this normal? Can we have an option to delete dynamodb as well?

Anything else I need to manually delete from AWS Console?

**Comment by christophgysin** [comment] 2017-09-24 06:18
Duplicate of #144.

**Closed by christophgysin** 2017-09-24 06:18 UTC

**Comment by ozbillwang** [comment] 2017-09-24 07:45
Thanks, @christophgysin 

My further question is, how can set `DeletionPolicy: Retain` as an option for different environments in `serverless.yml`? 

Such as for non-prod (dev/stag/uat) environments, I'd like to set to `not retain`, for production, set to `Retain.
